drop table iomap if exists;
drop table project if exists;
drop table requirement if exists;
drop table task if exists;
drop table task_circular_dependency_array if exists;
drop table task_priority_array if exists;

create table iomap (
    id bigint generated by default as identity,
    io_name varchar(255),
    io_number varchar(255),
    project_id bigint not null,
    primary key (id)
) engine=InnoDB default charset=utf8;

create table project (
    id bigint generated by default as identity,
    description varchar(255),
    name varchar(255) not null,
    primary key (id)
) engine=InnoDB default charset=utf8;

create table requirement (
    id bigint generated by default as identity,
    disabled boolean not null,
    error_description varchar(255),
    project bigint not null,
    state varchar(255) not null,
    text varchar(255) not null,
    primary key (id)
) engine=InnoDB default charset=utf8;

create table task (
    project_id bigint not null,
    code varchar(255),
    description varchar(255),
    requirements varchar(255),
    status varchar(255),
    timestamp timestamp not null,
    primary key (project_id)
) engine=InnoDB default charset=utf8;

create table task_circular_dependency_array (
    task_project_id bigint not null,
    circular_dependency_array varchar(255),
    foreign key (task_project_id) references task (project_id)
) engine=InnoDB default charset=utf8;

create table task_priority_array (
    task_project_id bigint not null,
    priority_array varchar(255),
    foreign key (task_project_id) references task (project_id)
) engine=InnoDB default charset=utf8;



